### PR TITLE
fix: crash while updating #282

### PR DESCRIPTION
**Pull request by Miaoyww**
a simple issue for not using scheduler to wait for thread joining.

maybe there is another wonderful way to fix it

### CODE REVIEW

**Comment by Miaoyww** [comment]
#282

**Comment by titivermeesch** [comment]
Thanks for this. This indeed seems like it would resolve the problem. Would you mind updating the version from 8.7.4 to 8.7.5? There is no automatic process for it yet. The version is in the plugin.yml file and all the gradle build files.
If that's done I can approve and merge

**Comment by Miaoyww** [comment]
> Thanks for this. This indeed seems like it would resolve the problem. Would you mind updating the version from 8.7.4 to 8.7.5? There is no automatic process for it yet. The version is in the plugin.yml file and all the gradle build files. If that's done I can approve and merge

done

**Comment by titivermeesch** [comment]
Can you also update the gradle build files? The version is mentioned twice in each gradle build file (there are 3 files in total)
- https://github.com/titivermeesch/CommandTimer/blob/main/java8-build.gradle
- https://github.com/titivermeesch/CommandTimer/blob/main/java17-build.gradle
- https://github.com/titivermeesch/CommandTimer/blob/main/build.gradle

**Comment by Miaoyww** [comment]
> Can you also update the gradle build files? The version is mentioned twice in each gradle build file (there are 3 files in total)
> 
> * https://github.com/titivermeesch/CommandTimer/blob/main/java8-build.gradle
> * https://github.com/titivermeesch/CommandTimer/blob/main/java17-build.gradle
> * https://github.com/titivermeesch/CommandTimer/blob/main/build.gradle

sorry i misses those.I just got home and was a bit inattentive😂

**Pull request merged**
